services:
  bitcoind:
    container_name: bitcoin
    image: btcpayserver/bitcoin:26.0
    restart: unless-stopped
    expose:
      - '43782'
      - '39388'
    ports:
      - '43782:43782'
      - '39388:39388'
    volumes:
      - 'bitcoin_home:/home/bitcoin/.bitcoin'
    environment:
      BITCOIN_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      CREATE_WALLET: 'true'
      BITCOIN_WALLETDIR: '/walletdata'
      BITCOIN_EXTRA_ARGS: |
        rpcport=43782
        rpcbind=0.0.0.0:43782
        rpcallowip=0.0.0.0/0
        port=39388
        whitelist=0.0.0.0/0
        maxmempool=500
        rpcauth=polaruser:5e5e98c21f5c814568f8b55d83b23c1c$$066b03f92df30b11de8e4b1b1cd5b1b4281aa25205bd57df9be82caf97a05526
        txindex=1
        fallbackfee=0.00001
        zmqpubrawblock=tcp://0.0.0.0:28334
        zmqpubrawtx=tcp://0.0.0.0:28335
        zmqpubhashblock=tcp://0.0.0.0:28336

  bitcoinsetup:
    image: btcpayserver/bitcoin:26.0
    depends_on:
      - bitcoind
    restart: 'no'
    volumes:
      - 'bitcoin_home:/home/bitcoin/.bitcoin'
    user: bitcoin
    # generate one block so electrs stop complaining
    entrypoint:
      [
        'bash',
        '-c',
        'sleep 1; while ! bitcoin-cli -rpcconnect=bitcoind -generate 1; do sleep 1; done',
      ]

  electrs:
    container_name: electrum
    image: getumbrel/electrs:v0.10.2
    restart: unless-stopped
    depends_on:
      - bitcoind
    expose:
      - '60001'
      - '28334'
      - '28335'
      - '28336'
    ports:
      - '60001:60001'
      # - '28334:28334'
      # - '28335:28335'
      # - '28336:28336'
    volumes:
      - './electrs.toml:/data/electrs.toml'
    environment:
      - ELECTRS_NETWORK=regtest
      - ELECTRS_ELECTRUM_RPC_ADDR=electrs:60001
      - ELECTRS_DAEMON_RPC_ADDR=bitcoind:43782
      - ELECTRS_DAEMON_P2P_ADDR=bitcoind:39388
      - ELECTRS_LOG_FILTERS=INFO


volumes:
  bitcoin_home:

networks: {}
